version: "3.8"

services:
  subtensor-localnet:
    container_name: bittensor-basic-subnet
    image: hamzatrq/hip-subnet:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./blockchain:/tmp/blockchain
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    command:
      - /bin/bash
      # - -c
      # - |
      #   /subtensor/scripts/localnet.sh